import type { Config } from 'tailwindcss'

const config: Config = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        "surface": "#ffffff",
        "surface-dim": "#c8d5f5",
        "surface-bright": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f7ff",
        "surface-container": "#eef2ff",
        "surface-container-high": "#e1e8ff",
        "surface-container-highest": "#d4dfff",
        "on-surface": "#0b1829",
        "on-surface-variant": "#4b5675",
        "inverse-surface": "#1e2e50",
        "inverse-on-surface": "#eef2ff",
        "outline": "#8b9abf",
        "outline-variant": "#d4dfff",
        "surface-tint": "#1a56db",
        "primary": "#1a56db",
        "on-primary": "#ffffff",
        "primary-container": "#ebf0ff",
        "on-primary-container": "#1a56db",
        "inverse-primary": "#93b4ff",
        "secondary": "#0acf83",
        "on-secondary": "#ffffff",
        "secondary-container": "#d1fae8",
        "on-secondary-container": "#065c38",
        "tertiary": "#6366f1",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#eef0ff",
        "on-tertiary-container": "#3730a3",
        "error": "#dc2626",
        "on-error": "#ffffff",
        "error-container": "#fee2e2",
        "on-error-container": "#7f1d1d",
        "background": "#f0f4ff",
        "on-background": "#0b1829",
        "surface-variant": "#d4dfff",
        "primary-fixed": "#dce8ff",
        "primary-fixed-dim": "#93b4ff",
        "on-primary-fixed": "#001a54",
        "on-primary-fixed-variant": "#0f3bb5",
        "secondary-fixed": "#b3f5d8",
        "secondary-fixed-dim": "#06b571",
        "on-secondary-fixed": "#002113",
        "on-secondary-fixed-variant": "#065c38",
        "tertiary-fixed": "#e0e7ff",
        "tertiary-fixed-dim": "#a5b4fc",
        "on-tertiary-fixed": "#1e1b4b",
        "on-tertiary-fixed-variant": "#3730a3",
      },
      borderRadius: {
        "sm": "0.25rem",
        "DEFAULT": "0.5rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "2xl": "1rem",
        "full": "9999px",
      },
      spacing: {
        "base": "8px",
        "stack-sm": "12px",
        "stack-md": "24px",
        "stack-lg": "48px",
        "gutter": "24px",
        "margin": "32px",
        "container-max": "1280px",
      },
      fontFamily: {
        sans: ['Manrope', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '1.4', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-sm': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-md': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '700' }],
      },
      backgroundImage: {
        'brand-gradient': 'linear-gradient(135deg, #0f3bb5 0%, #1a56db 50%, #2563eb 100%)',
        'brand-gradient-subtle': 'linear-gradient(135deg, #ebf0ff 0%, #f0f4ff 100%)',
        'green-gradient': 'linear-gradient(135deg, #059669 0%, #0acf83 100%)',
      },
      boxShadow: {
        'card': '0 1px 3px 0 rgba(26,86,219,0.06), 0 1px 2px 0 rgba(26,86,219,0.04)',
        'card-hover': '0 4px 16px 0 rgba(26,86,219,0.12), 0 1px 4px 0 rgba(26,86,219,0.06)',
        'header': '0 1px 0 0 #d4dfff',
      },
    },
  },
  plugins: [],
}
export default config
